### ISSUE TITLE
NameError:name 'unicode' is not defined

### ISSUE THREAD

**Issue by fyezool** [BookFusion/calibre-plugin#1]
Got this error when i try to key in my bookfusion API on Calibre.

```
calibre, version 4.99.4
ERROR: Unhandled exception: <b>NameError</b>:name 'unicode' is not defined

calibre 4.99.4  embedded-python: False is64bit: True
Linux-5.4.0-42-generic-x86_64-with-glibc2.29 Linux ('64bit', 'ELF')
('Linux', '5.4.0-42-generic', '#46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020')
Python 3.8.2
Interface language: None
Successfully initialized third party plugins: BookFusion Plugin (0, 4, 2)
Traceback (most recent call last):
  File "calibre_plugins.bookfusion.sync", line 96, in config
  File "/usr/lib/calibre/calibre/customize/__init__.py", line 178, in do_user_config
    self.save_settings(config_widget)
  File "calibre_plugins.bookfusion.__init__", line 25, in save_settings
  File "calibre_plugins.bookfusion.config", line 67, in save_settings
NameError: name 'unicode' is not defined
```

OS : Ubuntu 20
Python Version 3.8.2

**Comment by skillachie** [comment]
Hi @fyezool,

Thank you for reporting. We will investigate and get back to you shortly.

Best,
Dwayne

**Comment by skillachie** [comment]
Hey @fyezool ,

The issue was that our plugin did not support Python 3 and therefore the beta version of Calibre. We are currently finalizing the next update that should resolve your issue. 

Can you give this version a try and let us know if it resolved your issues?  https://github.com/BookFusion/calibre-plugin/releases/download/v0.5.1/BookFusion.zip

Best,
Dwayne

**Comment by fyezool** [comment]
Cool, it works. Thanks
